on:
  release:
    types: [published]

name: Docker

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@master

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set git env
        run: |
          echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Make envfile
        run: |
          cat > .env
          echo "VITE_VERSION=${{ env.TAG_NAME }}" >> .env
          echo "VITE_V_DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> .env
          echo "$(<.env)"

      - name: Build and Push Docker Image
        run: |
          docker build . -t ${{ vars.REPOSITORY_NAME }}:${{ env.TAG_NAME }} --build-arg NPM_USER=${{ vars.NPM_USER }} --build-arg NPM_EMAIL=${{ vars.NPM_EMAIL }} --build-arg NPM_PASS=${{ secrets.NPM_PASS }} --build-arg NPM_URL=${{ vars.NPM_URL }}
          docker push ${{ vars.REPOSITORY_NAME }}:${{ env.TAG_NAME }}
